//! The custom-directive validator must agree with Python's, case by case.
//!
//! `validate_custom_nginx` is a security control: the block is written into
//! the server's own configuration, so a directive that slips through is a
//! `proxy_pass` to somebody else's host or a `root` pointing at `/etc`. The
//! Python expresses it as seven regular expressions and this project has no
//! regex dependency, so the port is hand-written scanning - the kind of port
//! that goes subtly wrong in one branch and passes every test written from
//! the same reading.
//!
//! So the cases are not written here. They are generated by running the real
//! Python over a corpus and recording its verdicts, and this replays them.

use serde_json::Value;
use snpanel_nginx::CustomDirectives;

#[test]
fn the_validator_agrees_with_python_on_every_captured_case() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/golden/nginx/custom_directives.json");
    let cases: Vec<Value> =
        serde_json::from_str(&std::fs::read_to_string(&path).expect("the captured verdicts"))
            .expect("the verdicts parse");
    assert!(
        cases.len() >= 70,
        "the corpus shrank to {} cases; it is the only witness this port has",
        cases.len()
    );

    let mut accepted = 0usize;
    let mut failures: Vec<String> = Vec::new();
    for case in &cases {
        let name = case["name"].as_str().expect("a case name");
        let input = case["input"].as_str().expect("an input");
        let python_ok = case["ok"].as_bool().expect("a verdict");
        if python_ok {
            accepted += 1;
        }

        match (CustomDirectives::validate(input), python_ok) {
            (Ok(got), true) => {
                let expected = case["value"].as_str().unwrap_or("");
                if got.as_str() != expected {
                    failures.push(format!(
                        "{name}: both accepted but the text differs\n    python: {expected:?}\n    rust:   {:?}",
                        got.as_str()
                    ));
                }
            }
            (Err(_), false) => {}
            (Ok(got), false) => failures.push(format!(
                "{name}: rust ACCEPTED what python refused ({})\n    input: {input:?}\n    kept:  {:?}",
                case["error"].as_str().unwrap_or("?"),
                got.as_str()
            )),
            (Err(e), true) => failures.push(format!(
                "{name}: rust refused what python accepted\n    input: {input:?}\n    rust:  {e}"
            )),
        }
    }

    assert!(
        accepted >= 15,
        "only {accepted} cases are accepted; a corpus that refuses everything \
         would pass a validator that refuses everything"
    );
    assert!(
        failures.is_empty(),
        "{} of {} cases disagree:\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n")
    );
}

/// The same comparison against a generated corpus.
///
/// The hand-picked cases all agreed on the first run, which is either a good
/// port or a corpus that does not reach the branches. These are the seeds
/// mutated in the ways that break a hand-written scanner - a directive after
/// a brace rather than a newline, odd whitespace, case changes, a truncated
/// statement - with the real Python's verdict recorded for each.
#[test]
fn the_validator_agrees_with_python_on_a_generated_corpus() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/golden/nginx/custom_directives_fuzz.json");
    let cases: Vec<Value> =
        serde_json::from_str(&std::fs::read_to_string(&path).expect("the fuzz corpus"))
            .expect("the corpus parses");
    assert!(cases.len() > 800, "the corpus shrank to {}", cases.len());

    let accepted = cases
        .iter()
        .filter(|c| c["ok"].as_bool().unwrap_or(false))
        .count();
    assert!(
        accepted > 100,
        "only {accepted} of {} are accepted; a corpus that refuses almost \
         everything would pass a validator that refuses everything",
        cases.len()
    );

    let mut failures: Vec<String> = Vec::new();
    for case in &cases {
        let name = case["name"].as_str().unwrap_or("?");
        let input = case["input"].as_str().expect("an input");
        let python_ok = case["ok"].as_bool().expect("a verdict");
        match (CustomDirectives::validate(input), python_ok) {
            (Ok(got), true) => {
                let expected = case["value"].as_str().unwrap_or("");
                if got.as_str() != expected {
                    failures.push(format!("{name}: text differs for {input:?}"));
                }
            }
            (Err(_), false) => {}
            (Ok(_), false) => failures.push(format!(
                "{name}: rust ACCEPTED what python refused ({}): {input:?}",
                case["error"].as_str().unwrap_or("?")
            )),
            (Err(e), true) => failures.push(format!(
                "{name}: rust refused what python accepted: {input:?} ({e})"
            )),
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} disagree:\n{}",
        failures.len(),
        cases.len(),
        failures
            .iter()
            .take(12)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}
