//! Validating a customer's nginx snippet before it is rendered inside a
//! `server { }` scope.
//!
//! Source: `validate_custom_nginx`. This is a security control, not a
//! convenience: the block is written into the server's own configuration, so
//! a directive that slips through is a `proxy_pass` to somebody else's host,
//! a `root` pointing at `/etc`, or an `access_log` writing wherever it likes.
//!
//! The Python expresses it as seven regular expressions. This project has no
//! regex dependency - `regex` is not in the lock file at all, and the
//! validators in `snpanel-core` are hand-written for the same reason - so
//! these are scanners. Hand-written matching of a security pattern is exactly
//! the kind of port that goes subtly wrong, which is why the tests are
//! generated by running the real Python over a corpus rather than written
//! from the same reading that produced the code.

use crate::RenderError;

/// A snippet that has been through [`CustomDirectives::validate`].
///
/// There is no other constructor. The renderer takes one of these rather than
/// a `&str` so that "did anybody validate this?" is not a question a reader
/// has to answer by tracing call sites.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct CustomDirectives(String);

pub type CustomError = RenderError;

impl CustomDirectives {
    /// The empty block, which is what a site with no custom directives has.
    pub fn empty() -> Self {
        Self(String::new())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }

    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// Source: `validate_custom_nginx`.
    pub fn validate(content: &str) -> Result<Self, CustomError> {
        if content.is_empty() {
            return Ok(Self(String::new()));
        }
        let text = content.replace("\r\n", "\n");
        let text = text.trim().to_string();
        if text.is_empty() {
            return Ok(Self(String::new()));
        }
        if text.len() > 16 * 1024 {
            return Err(err("Custom nginx block is too large"));
        }

        // Balanced braces, nesting allowed inside the server scope.
        let mut depth: i64 = 0;
        for ch in text.chars() {
            match ch {
                '{' => depth += 1,
                '}' => {
                    depth -= 1;
                    if depth < 0 {
                        return Err(err("Unbalanced braces in custom nginx block"));
                    }
                }
                _ => {}
            }
        }
        if depth != 0 {
            return Err(err("Unbalanced braces in custom nginx block"));
        }

        if has_dangerous_block(&text) {
            return Err(err(
                "Custom block must not nest server/http/events/stream/upstream blocks",
            ));
        }

        // Normalise so the line-anchored deny-list also catches directives
        // written on the same line as their enclosing block.
        let normalized: String = text
            .chars()
            .map(|c| {
                if matches!(c, '{' | '}' | ';') {
                    '\n'
                } else {
                    c
                }
            })
            .collect();
        if has_dangerous_directive(&normalized) {
            return Err(err(
                "Custom block must not contain disallowed directives (proxy_pass, alias, \
                 return, ssl_certificate, ...)",
            ));
        }

        let add_header_count = count_directive(&text, "add_header");
        let add_header_names = add_header_names(&text);
        if add_header_count != add_header_names.len() {
            return Err(err("Malformed or unsupported add_header directive"));
        }
        let mut unsupported: Vec<String> = add_header_names
            .iter()
            .filter(|h| !CACHE_HEADER_NAMES.contains(&h.to_lowercase().as_str()))
            .cloned()
            .collect();
        unsupported.sort_by_key(|h| h.to_lowercase());
        unsupported.dedup();
        if !unsupported.is_empty() {
            return Err(err(format!(
                "Custom add_header may only set cache-related headers; disallowed: {}",
                unsupported.join(", ")
            )));
        }

        let try_files = try_files_arguments(&text);
        for arguments in &try_files {
            let tokens: Vec<&str> = arguments.split_whitespace().collect();
            let bad = tokens.is_empty()
                || tokens.iter().any(|t| {
                    t.starts_with("file:")
                        || t.starts_with("http:")
                        || t.starts_with("https:")
                        || t.split('/').any(|seg| seg == "..")
                });
            if bad {
                return Err(err(
                    "Custom try_files directives must not use traversal or external URLs",
                ));
            }
        }
        if count_directive(&text, "try_files") != try_files.len() {
            return Err(err("Malformed or unsupported try_files directive"));
        }

        let rewrites = rewrite_statements(&text);
        for (replacement, flag) in &rewrites {
            let bad = !replacement.starts_with('/')
                || replacement.starts_with("//")
                || replacement.contains("://")
                || replacement.split('/').any(|seg| seg == "..")
                || flag.as_ref().is_some_and(|f| f != "last" && f != "break");
            if bad {
                return Err(err(
                    "Custom rewrite directives must target a local URI and use last or break",
                ));
            }
        }
        if count_directive(&text, "rewrite") != rewrites.len() {
            return Err(err("Malformed or unsupported rewrite directive"));
        }

        if text.contains('\0') {
            return Err(err("Custom nginx block contains a NUL byte"));
        }
        Ok(Self(text))
    }
}

fn err(message: impl Into<String>) -> CustomError {
    RenderError::Invalid(message.into())
}

/// Source: `CACHE_HEADER_NAMES`.
const CACHE_HEADER_NAMES: &[&str] = &[
    "cache-control",
    "cdn-cache-control",
    "expires",
    "pragma",
    "surrogate-control",
    "vary",
    "x-cache",
    "x-cache-status",
    "x-fastcgi-cache",
];

/// `\s` as Python's `re` module means it for a `str` pattern.
fn is_space(b: u8) -> bool {
    matches!(b, b' ' | b'\t' | b'\n' | b'\r' | 0x0b | 0x0c)
}

fn is_word(b: u8) -> bool {
    b.is_ascii_alphanumeric() || b == b'_'
}

/// Case-insensitive `text[at..].starts_with(word)`.
fn word_at(text: &[u8], at: usize, word: &str) -> bool {
    let w = word.as_bytes();
    if at + w.len() > text.len() {
        return false;
    }
    text[at..at + w.len()]
        .iter()
        .zip(w)
        .all(|(a, b)| a.eq_ignore_ascii_case(b))
}

fn skip_space(text: &[u8], mut at: usize) -> usize {
    while at < text.len() && is_space(text[at]) {
        at += 1;
    }
    at
}

/// Positions a `(?:^|[;{}])` alternation can match: the start of the string,
/// just after a newline, and just after `;`, `{` or `}`.
fn anchor_positions(text: &[u8]) -> Vec<usize> {
    let mut out = vec![0usize];
    for (i, b) in text.iter().enumerate() {
        if matches!(b, b'\n' | b';' | b'{' | b'}') {
            out.push(i + 1);
        }
    }
    out
}

/// Positions `^` matches under `re.MULTILINE`.
fn line_starts(text: &[u8]) -> Vec<usize> {
    let mut out = vec![0usize];
    for (i, b) in text.iter().enumerate() {
        if *b == b'\n' {
            out.push(i + 1);
        }
    }
    out
}

/// Source: `(?mi)(?:^|[;{}])\s*<name>\b` - how many times the directive is
/// written at all, well-formed or not.
fn count_directive(text: &str, name: &str) -> usize {
    let bytes = text.as_bytes();
    let mut seen: Vec<usize> = Vec::new();
    for anchor in anchor_positions(bytes) {
        let at = skip_space(bytes, anchor);
        if word_at(bytes, at, name) {
            let after = at + name.len();
            if after >= bytes.len() || !is_word(bytes[after]) {
                // Two anchors can reach the same directive (a newline right
                // after a `;`), and the regex engine would only match it once.
                if !seen.contains(&at) {
                    seen.push(at);
                }
            }
        }
    }
    seen.len()
}

/// Source: `DANGEROUS_BLOCKS`.
fn has_dangerous_block(text: &str) -> bool {
    let bytes = text.as_bytes();
    // `(?:^|[;{}\s])` - note this one also allows any whitespace.
    let anchors = (0..=bytes.len()).filter(|i| {
        *i == 0 || matches!(bytes[i - 1], b';' | b'{' | b'}') || is_space(bytes[i - 1])
    });
    for anchor in anchors {
        let at = skip_space(bytes, anchor);
        for keyword in ["server", "http", "events", "stream"] {
            if word_at(bytes, at, keyword) {
                let brace = skip_space(bytes, at + keyword.len());
                if brace < bytes.len() && bytes[brace] == b'{' {
                    return true;
                }
            }
        }
        if word_at(bytes, at, "upstream") {
            let mut j = at + "upstream".len();
            let before = j;
            j = skip_space(bytes, j);
            if j == before {
                continue; // `\s+` needs at least one space
            }
            // `[@A-Za-z0-9_][A-Za-z0-9_]*`
            if j < bytes.len() && (bytes[j] == b'@' || is_word(bytes[j])) {
                j += 1;
                while j < bytes.len() && is_word(bytes[j]) {
                    j += 1;
                }
                let brace = skip_space(bytes, j);
                if brace < bytes.len() && bytes[brace] == b'{' {
                    return true;
                }
            }
        }
    }
    false
}

/// Source: `DANGEROUS_DIRECTIVES`, in the order the Python lists them.
///
/// Three shapes: a name that must be followed by whitespace, a name that must
/// end on a word boundary, and a bare prefix that matches any directive
/// starting with it.
const DANGEROUS_SPACE: &[&str] = &[
    "include",
    "user",
    "daemon",
    "pid",
    "alias",
    "root",
    "access_log",
    "error_log",
    "return",
    "error_page",
];
const DANGEROUS_BOUNDARY: &[&str] = &[
    "load_module",
    "working_directory",
    "pcre_jit",
    "proxy_pass",
    "fastcgi_pass",
    "uwsgi_pass",
    "scgi_pass",
    "grpc_pass",
    "auth_basic_user_file",
    "more_set_headers",
    "more_clear_headers",
    "auth_request",
    "sub_filter",
    "sub_filter_once",
    "addition_before_body",
    "addition_after_body",
    "ssl_certificate",
    "ssl_certificate_key",
    "ssl_trusted_certificate",
];
const DANGEROUS_PREFIX: &[&str] = &["lua_", "perl_", "js_"];

fn has_dangerous_directive(text: &str) -> bool {
    let bytes = text.as_bytes();
    for start in line_starts(bytes) {
        let at = skip_space(bytes, start);
        for name in DANGEROUS_SPACE {
            if word_at(bytes, at, name) {
                let after = at + name.len();
                if after < bytes.len() && is_space(bytes[after]) {
                    return true;
                }
            }
        }
        for name in DANGEROUS_BOUNDARY {
            if word_at(bytes, at, name) {
                let after = at + name.len();
                if after >= bytes.len() || !is_word(bytes[after]) {
                    return true;
                }
            }
        }
        for name in DANGEROUS_PREFIX {
            if word_at(bytes, at, name) {
                return true;
            }
        }
    }
    false
}

/// Source: `ADD_HEADER_NAME_RE` - the header names of well-formed directives.
///
/// The name charset is RFC 7230's token, and the lookahead requires
/// whitespace after it, so `add_header Cache-Control;` yields nothing and the
/// count check then rejects the block.
fn add_header_names(text: &str) -> Vec<String> {
    const TOKEN: &[u8] = b"!#$%&'*+-.^_`|~";
    let bytes = text.as_bytes();
    let mut out: Vec<String> = Vec::new();
    let mut seen: Vec<usize> = Vec::new();
    for anchor in anchor_positions(bytes) {
        let at = skip_space(bytes, anchor);
        if !word_at(bytes, at, "add_header") {
            continue;
        }
        let mut j = at + "add_header".len();
        let before = j;
        j = skip_space(bytes, j);
        if j == before {
            continue; // `\s+`
        }
        let name_start = j;
        while j < bytes.len() && (bytes[j].is_ascii_alphanumeric() || TOKEN.contains(&bytes[j])) {
            j += 1;
        }
        if j == name_start {
            continue;
        }
        // `(?=\s)`
        if j >= bytes.len() || !is_space(bytes[j]) {
            continue;
        }
        if seen.contains(&at) {
            continue;
        }
        seen.push(at);
        out.push(String::from_utf8_lossy(&bytes[name_start..j]).into_owned());
    }
    out
}

/// Source: `TRY_FILES_RE` - `^\s*try_files\s+([^;{}]+);`, the argument text.
fn try_files_arguments(text: &str) -> Vec<String> {
    let bytes = text.as_bytes();
    let mut out = Vec::new();
    for start in line_starts(bytes) {
        let at = skip_space(bytes, start);
        if !word_at(bytes, at, "try_files") {
            continue;
        }
        let mut j = at + "try_files".len();
        let before = j;
        j = skip_space(bytes, j);
        if j == before {
            continue;
        }
        let arg_start = j;
        while j < bytes.len() && !matches!(bytes[j], b';' | b'{' | b'}') {
            j += 1;
        }
        if j < bytes.len() && bytes[j] == b';' && j > arg_start {
            out.push(String::from_utf8_lossy(&bytes[arg_start..j]).into_owned());
        }
    }
    out
}

/// Source: `^\s*rewrite\s+\S+\s+(\S+)(?:\s+(\S+))?\s*;` - the replacement and
/// the optional flag of every well-formed rewrite.
///
/// `\S+` includes `;`, and the engine backtracks. That is not a detail: for
/// `rewrite ^/a/(.*)$ /b/$1 last;;` the flag group takes `last;` and the
/// trailing `;` closes the statement, so Python reads the flag as `last;`
/// and refuses it. A scanner that stops fields at `;` reads `last` and
/// accepts - which is what this did until a generated corpus put a double
/// semicolon in front of it.
///
/// So the backtracking is reproduced rather than approximated: the flag is
/// the longest run of non-whitespace that still leaves a `;` to terminate the
/// statement, and the optional group is tried before the empty alternative.
fn rewrite_statements(text: &str) -> Vec<(String, Option<String>)> {
    let bytes = text.as_bytes();
    let mut out = Vec::new();
    for start in line_starts(bytes) {
        let at = skip_space(bytes, start);
        if !word_at(bytes, at, "rewrite") {
            continue;
        }
        let mut j = at + "rewrite".len();
        // `\s+` before the pattern.
        let before = j;
        j = skip_space(bytes, j);
        if j == before {
            continue;
        }
        // `\S+` - the pattern. It cannot cross whitespace, and what follows
        // it must be whitespace, so there is nothing to backtrack here.
        let p1 = j;
        while j < bytes.len() && !is_space(bytes[j]) {
            j += 1;
        }
        if j == p1 {
            continue;
        }
        // `\s+` before the replacement.
        let before = j;
        j = skip_space(bytes, j);
        if j == before {
            continue;
        }
        let p2 = j;
        let mut e2 = j;
        while e2 < bytes.len() && !is_space(bytes[e2]) {
            e2 += 1;
        }
        if e2 == p2 {
            continue;
        }

        // The replacement, longest first.
        let mut matched: Option<(String, Option<String>)> = None;
        'outer: for end2 in (p2 + 1..=e2).rev() {
            let replacement = String::from_utf8_lossy(&bytes[p2..end2]).into_owned();

            // `(?:\s+(\S+))?` can only participate when the replacement ran
            // to the end of its run - otherwise the next character is not
            // whitespace.
            if end2 == e2 {
                let p3 = skip_space(bytes, e2);
                if p3 > e2 && p3 < bytes.len() && !is_space(bytes[p3]) {
                    let mut e3 = p3;
                    while e3 < bytes.len() && !is_space(bytes[e3]) {
                        e3 += 1;
                    }
                    for end3 in (p3 + 1..=e3).rev() {
                        if terminates(bytes, end3, e3) {
                            matched = Some((
                                replacement.clone(),
                                Some(String::from_utf8_lossy(&bytes[p3..end3]).into_owned()),
                            ));
                            break 'outer;
                        }
                    }
                }
            }
            // The empty alternative: `\s*;` straight after the replacement.
            if terminates(bytes, end2, e2) {
                matched = Some((replacement, None));
                break 'outer;
            }
        }
        if let Some(found) = matched {
            out.push(found);
        }
    }
    out
}

/// `\s*;` at `end`.
///
/// When `end` is inside the run, the next character is not whitespace, so
/// `\s*` matches nothing and the `;` has to be right there. When it is at the
/// end of the run, whitespace may be skipped first - including newlines,
/// because `\s` matches those too.
fn terminates(bytes: &[u8], end: usize, run_end: usize) -> bool {
    let at = if end < run_end {
        end
    } else {
        skip_space(bytes, end)
    };
    at < bytes.len() && bytes[at] == b';'
}
