#!/usr/bin/env python3
"""gen_apache.py [--version-handler|--selector]

Hand-written stand-in for what snpanel-web's Apache renderer will do: one
vhost per site under /etc/httpd/snpanel/sites/, reproducing the behaviour of
the nginx templates (checked by probe.py), with PHP served by mod_lsapi.

--version-handler (default): SetHandler application/x-httpd-alt-phpXX___lsphp,
    pinned to the version the site runs today. Used for the cutover, so no
    site changes PHP version while the web server changes.
--selector: SetHandler application/x-httpd-lsphp, i.e. whatever the owner's
    PHP Selector says (only meaningful once the owner is in CageFS).
"""
import json
import os
import subprocess
import sys

MODE = "selector" if "--selector" in sys.argv else "version"
OUT = "/etc/httpd/snpanel/sites"

HEADERS = """\
    Header always set X-Frame-Options "SAMEORIGIN"
    Header always set X-Content-Type-Options "nosniff"
    Header always set Referrer-Policy "strict-origin-when-cross-origin"
    Header always set X-XSS-Protection "1; mode=block"
    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
    Header always set Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=(), usb=(), bluetooth=(), magnetometer=(), gyroscope=(), accelerometer=()"
    Header always set Content-Security-Policy "default-src 'self' https: data: blob:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https: blob:; font-src 'self' data: https:; connect-src 'self' https:; frame-src 'self' https: blob:; worker-src 'self' blob:; object-src 'none'; base-uri 'self'; form-action 'self' https:; frame-ancestors 'self'; upgrade-insecure-requests"
"""

# Same list as the nginx `location ~* \.(?:sql|bak|...)$ { deny all; }`
DENY_EXT = r"\.(?:sql|bak|backup|old|orig|save|swp|swo|ini|log|conf|env|sh|inc)$"


def handler(version: str) -> str:
    if MODE == "selector":
        return "application/x-httpd-lsphp"
    return f"application/x-httpd-alt-php{version.replace('.', '')}___lsphp"


def vhost(s: dict) -> str:
    d = s["domain"]
    user = s["linux_user"]
    site_root = s["root_path"]
    docroot = os.path.join(site_root, s["document_root"])
    if s["nginx_rewrite_mode"] == "laravel":
        docroot = os.path.join(docroot, "public")
    names = [f"www.{d}"] + [a["domain"] for a in s.get("aliases", []) if a["mode"] == "alias"]
    app = s["app_type"]
    php = app in ("php", "wordpress")
    lines = [
        "# SNPANEL MANAGED VHOST - generated by gen_apache.py (CL-0 prototype)",
        "<VirtualHost *:80>",
        f"    ServerName {d}",
        f"    ServerAlias {' '.join(names)}",
        f"    DocumentRoot {docroot}",
        "    DirectoryIndex index.php index.html",
        f"    ErrorLog /var/log/httpd/{d}.error.log",
        f"    CustomLog /var/log/httpd/{d}.access.log combined",
        "    LimitRequestBody 1153433600",
        HEADERS.rstrip("\n"),
        "    Alias /.well-known/acme-challenge/ /var/www/snpanel-acme/.well-known/acme-challenge/",
        "    <Directory /var/www/snpanel-acme/.well-known/acme-challenge/>",
        "        Options None",
        "        AllowOverride None",
        "        ForceType text/plain",
        "        Require all granted",
        "    </Directory>",
    ]
    if php:
        lines += [f"    SuexecUserGroup {user} {user}"]
    lines += [
        f"    <Directory {site_root}>",
        "        Options -Indexes -FollowSymLinks +SymLinksIfOwnerMatch",
        "        AllowOverride FileInfo Options=Indexes,FollowSymLinks,SymLinksIfOwnerMatch Limit Indexes",
        "        Require all granted",
        "    </Directory>",
        # dotfiles except .well-known (nginx: location ~ /\.(?!well-known))
        '    <LocationMatch "/\\.(?!well-known)">',
        "        Require all denied",
        "    </LocationMatch>",
    ]
    if app != "static":
        lines += [
            f'    <FilesMatch "{DENY_EXT}">',
            "        Require all denied",
            "    </FilesMatch>",
        ]
    if app == "wordpress":
        lines += [
            '    <FilesMatch "^(?:xmlrpc\\.php|wp-config\\.php|readme\\.html|license\\.txt)$">',
            "        Require all denied",
            "    </FilesMatch>",
            '    <LocationMatch "(?i)/(?:uploads|files)/.*\\.php$">',
            "        Require all denied",
            "    </LocationMatch>",
            '    <LocationMatch "(?i)^/(?:wp-admin/includes|wp-includes)/.*\\.php$">',
            "        Require all denied",
            "    </LocationMatch>",
        ]
    if app == "static":
        # LocationMatch, not FilesMatch: nginx refuses *.php on a static site
        # whether or not the file exists (403, never 404)
        lines += [
            '    <LocationMatch "(?i)\\.(?:php[0-9]?|phtml)$">',
            "        Require all denied",
            "    </LocationMatch>",
        ]
    if php:
        lines += [
            '    <FilesMatch "\\.(?:php|phtml)$">',
            f"        SetHandler {handler(s['php_version'])}",
            "    </FilesMatch>",
        ]
        # front controller for WordPress and laravel, in the vhost so it does
        # not depend on the customer's .htaccess (nginx: try_files ... /index.php)
        if app == "wordpress" or s["nginx_rewrite_mode"] in ("laravel", "front_controller"):
            lines += [
                "    RewriteEngine On",
                "    RewriteCond %{REQUEST_URI} !^/\\.well-known/",
                "    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} !-f",
                "    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} !-d",
                "    RewriteRule ^ /index.php [L]",
            ]
    lines += ["</VirtualHost>", ""]
    return "\n".join(lines)


def main() -> None:
    sites = json.loads(subprocess.check_output(["/root/api.sh", "GET", "/websites"]))
    os.makedirs(OUT, exist_ok=True)
    for f in os.listdir(OUT):
        if f.endswith(".conf"):
            os.unlink(os.path.join(OUT, f))
    for s in sites:
        with open(os.path.join(OUT, f"{s['domain']}.conf"), "w") as f:
            f.write(vhost(s))
    print(f"{len(sites)} vhosts ({MODE} handler) -> {OUT}")


main()
