//! The nftables backend.
//!
//! Plan §6.3. The plan gives the reason as "`ipset` is deprecated on RHEL 10",
//! and that turns out not to be accurate: on AlmaLinux 10.2 `ipset` is
//! packaged and current (7.22-13.el10_2). What RHEL 10 has actually dropped is
//! **legacy iptables** - `iptables` and `iptables-legacy` are not packaged at
//! all, and `dnf install iptables` gives you `iptables-nft`, a translation
//! shim reporting `iptables v1.8.11 (nf_tables)`.
//!
//! So this is not the hard blocker the plan describes; the old backend would
//! probably run through the shim. It is still the right thing to build. The
//! panel would otherwise be generating iptables syntax for a kernel that only
//! speaks nftables, through a compatibility layer with its own edges, and
//! nftables is then used on *every* distribution - one code path to test
//! rather than two.
//!
//! The chain below reproduces `firewall_apply_family` in the bash helper rule
//! for rule, in the same order. Order is not cosmetic here - an allow that
//! lands after a drop is an allow that never fires.
//!
//! Three things the sketch in plan §6.3 leaves out, all of which the bash does
//! and all of which matter:
//!
//! 1. `ct state invalid drop` - present in the bash, absent from the sketch.
//! 2. An ICMP `return`. Dropping ICMPv6 breaks neighbour discovery, i.e. it
//!    breaks IPv6 outright. The bash has a comment saying exactly this.
//! 3. The `denyp*` sets (deny a source *and* port). The sketch has only the
//!    whole-host deny sets, which would silently widen every port-scoped deny
//!    rule into a whole-host one.
//!
//! C38 is preserved: allowed traffic uses `return`, not `accept`, so fail2ban
//! and any other `input` rules still see the packet.
//! C39 is preserved: disabling removes the jump and leaves the chain and its
//! counters in place, rather than flipping the policy.

use std::fmt::Write;

use super::rules::{Action, FirewallRuleset, FirewallState};

/// The table every SNPanel rule lives in. `inet` covers v4 and v6 in one table,
/// which is simpler than the two parallel iptables/ip6tables chains today.
pub const TABLE: &str = "snpanel";

/// Rendered as a single `nft -f` input so the load is atomic: either the whole
/// ruleset applies or none of it does. That is a real improvement over the
/// bash, which could leave a half-rebuilt chain if it failed midway - but it
/// is an improvement in the *mechanism*, not in the rules, so NT1 holds.
pub fn render(rs: &FirewallRuleset) -> String {
    let mut out = String::with_capacity(4096);

    out.push_str("#!/usr/sbin/nft -f\n");
    out.push_str("# Generated by snpanel. Do not edit: rebuilt from\n");
    out.push_str("# /var/lib/snpanel/firewall/rules.tsv on every change.\n\n");

    // `nft -f` MERGES into an existing table - it does not replace it. Without
    // this, every apply appends another `jump snpanel_input` to the base chain
    // and re-adds every rule, so the ruleset grows without bound; and a
    // disable never removes the hook, because the base chain from the previous
    // apply survives. Both were observed on a running box after eight applies.
    //
    // The empty declaration is there so the delete cannot fail on the first
    // run, when there is no table yet. All three statements are in the one
    // file, so `nft -f` still applies them as a single transaction.
    let _ = writeln!(out, "table inet {TABLE} {{}}");
    let _ = writeln!(out, "delete table inet {TABLE}\n");

    let _ = writeln!(out, "table inet {TABLE} {{");

    render_sets(&mut out, rs);
    render_chains(&mut out, rs);

    out.push_str("}\n");
    out
}

fn render_sets(out: &mut String, rs: &FirewallRuleset) {
    let v4_sets = [
        ("allow4", rs.host_rules(Action::Allow, false)),
        ("deny4", rs.host_rules(Action::Deny, false)),
    ];
    for (name, entries) in v4_sets {
        render_addr_set(out, name, "ipv4_addr", &render_entries(&entries));
    }
    render_addr_set(
        out,
        "block4",
        "ipv4_addr",
        &rs.blocklist_v4
            .iter()
            .map(|i| i.to_string())
            .collect::<Vec<_>>(),
    );

    render_port_set(out, "allowp4", "ipv4_addr", rs, Action::Allow, false);
    render_port_set(out, "denyp4", "ipv4_addr", rs, Action::Deny, false);

    if rs.ipv6_enabled {
        let v6_sets = [
            ("allow6", rs.host_rules(Action::Allow, true)),
            ("deny6", rs.host_rules(Action::Deny, true)),
        ];
        for (name, entries) in v6_sets {
            render_addr_set(out, name, "ipv6_addr", &render_entries(&entries));
        }
        render_addr_set(
            out,
            "block6",
            "ipv6_addr",
            &rs.blocklist_v6
                .iter()
                .map(|i| i.to_string())
                .collect::<Vec<_>>(),
        );
        render_port_set(out, "allowp6", "ipv6_addr", rs, Action::Allow, true);
        render_port_set(out, "denyp6", "ipv6_addr", rs, Action::Deny, true);
    }

    // Protected ports: SSH, the panel port, 80/443/465/587.
    let ports: Vec<String> = rs.protected_ports.iter().map(u16::to_string).collect();
    let _ = writeln!(out, "    set protected {{");
    let _ = writeln!(out, "        type inet_service");
    let _ = writeln!(out, "        flags interval");
    if !ports.is_empty() {
        let _ = writeln!(out, "        elements = {{ {} }}", ports.join(", "));
    }
    let _ = writeln!(out, "    }}\n");

    // Port-only allow rules, split by protocol.
    for (name, proto) in [("open_tcp", "tcp"), ("open_udp", "udp")] {
        let elements: Vec<String> = rs
            .open_ports()
            .iter()
            .filter(|r| r.protocol.as_str() == proto)
            .filter_map(|r| r.port.map(|p| p.to_string()))
            .collect();
        let _ = writeln!(out, "    set {name} {{");
        let _ = writeln!(out, "        type inet_service");
        let _ = writeln!(out, "        flags interval");
        if !elements.is_empty() {
            let _ = writeln!(out, "        elements = {{ {} }}", elements.join(", "));
        }
        let _ = writeln!(out, "    }}\n");
    }
}

fn render_entries(entries: &[&snpanel_core::IpOrCidr]) -> Vec<String> {
    entries.iter().map(|i| i.to_string()).collect()
}

fn render_addr_set(out: &mut String, name: &str, ty: &str, elements: &[String]) {
    let _ = writeln!(out, "    set {name} {{");
    let _ = writeln!(out, "        type {ty}");
    // `flags interval` is what lets one element be a CIDR range, which is the
    // ipset hash:net behaviour being replaced.
    let _ = writeln!(out, "        flags interval");
    // A URL blocklist can run to hundreds of thousands of entries.
    let _ = writeln!(out, "        auto-merge");
    if !elements.is_empty() {
        let _ = writeln!(out, "        elements = {{ {} }}", elements.join(", "));
    }
    let _ = writeln!(out, "    }}\n");
}

fn render_port_set(
    out: &mut String,
    name: &str,
    addr_ty: &str,
    rs: &FirewallRuleset,
    action: Action,
    ipv6: bool,
) {
    let elements: Vec<String> = rs
        .host_port_rules(action, ipv6)
        .iter()
        .filter_map(|r| {
            let ip = r.ip.as_ref()?;
            let port = r.port?;
            Some(format!("{ip} . {port}"))
        })
        .collect();
    let _ = writeln!(out, "    set {name} {{");
    // The concatenated type is the nft equivalent of ipset's hash:net,port.
    let _ = writeln!(out, "        type {addr_ty} . inet_service");
    let _ = writeln!(out, "        flags interval");
    if !elements.is_empty() {
        let _ = writeln!(out, "        elements = {{ {} }}", elements.join(", "));
    }
    let _ = writeln!(out, "    }}\n");
}

fn render_chains(out: &mut String, rs: &FirewallRuleset) {
    // C39: when disabled, the chain still exists with all its rules and
    // counters - it is simply not jumped to. The base chain is what carries
    // the hook, so it is the base chain that goes away.
    if rs.state == FirewallState::Enabled {
        let _ = writeln!(out, "    chain input {{");
        let _ = writeln!(
            out,
            "        type filter hook input priority filter; policy accept;"
        );
        let _ = writeln!(out, "        jump snpanel_input");
        let _ = writeln!(out, "    }}\n");
    } else {
        let _ = writeln!(
            out,
            "    # firewall disabled: no base chain, so snpanel_input is never"
        );
        let _ = writeln!(
            out,
            "    # consulted. The chain and its counters are kept (C39).\n"
        );
    }

    let _ = writeln!(out, "    chain snpanel_input {{");

    // Order below mirrors firewall_apply_family exactly.
    let _ = writeln!(out, "        iif lo return");
    let _ = writeln!(out, "        ct state established,related return");
    let _ = writeln!(out, "        ct state invalid drop");
    out.push('\n');

    let _ = writeln!(out, "        ip saddr @allow4 return");
    let _ = writeln!(out, "        ip saddr . tcp dport @allowp4 return");
    let _ = writeln!(out, "        ip saddr . udp dport @allowp4 return");
    if rs.ipv6_enabled {
        let _ = writeln!(out, "        ip6 saddr @allow6 return");
        let _ = writeln!(out, "        ip6 saddr . tcp dport @allowp6 return");
        let _ = writeln!(out, "        ip6 saddr . udp dport @allowp6 return");
    }
    out.push('\n');

    let _ = writeln!(out, "        ip saddr @deny4 drop");
    let _ = writeln!(out, "        ip saddr . tcp dport @denyp4 drop");
    let _ = writeln!(out, "        ip saddr . udp dport @denyp4 drop");
    let _ = writeln!(out, "        ip saddr @block4 drop");
    if rs.ipv6_enabled {
        let _ = writeln!(out, "        ip6 saddr @deny6 drop");
        let _ = writeln!(out, "        ip6 saddr . tcp dport @denyp6 drop");
        let _ = writeln!(out, "        ip6 saddr . udp dport @denyp6 drop");
        let _ = writeln!(out, "        ip6 saddr @block6 drop");
    }
    out.push('\n');

    // ICMPv6 carries neighbour discovery; dropping it breaks IPv6 entirely.
    let _ = writeln!(out, "        ip protocol icmp return");
    if rs.ipv6_enabled {
        let _ = writeln!(out, "        meta l4proto ipv6-icmp return");
    }
    out.push('\n');

    let _ = writeln!(out, "        tcp dport @protected return");
    let _ = writeln!(out, "        tcp dport @open_tcp return");
    let _ = writeln!(out, "        udp dport @open_udp return");

    if rs.state == FirewallState::Enabled {
        out.push('\n');
        let _ = writeln!(out, "        drop");
    }

    let _ = writeln!(out, "    }}");
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::firewall::rules::Rule;
    use snpanel_core::IpOrCidr;

    fn ruleset(tsv: &str) -> FirewallRuleset {
        FirewallRuleset {
            rules: FirewallRuleset::parse_rules_tsv(tsv),
            protected_ports: FirewallRuleset::compute_protected_ports(&[22], 2222),
            ..Default::default()
        }
    }

    #[test]
    fn the_ruleset_replaces_the_table_rather_than_merging_into_it() {
        // The regression this guards is not hypothetical: `nft -f` merges, so
        // without the delete, applying eight times left eight copies of
        // `jump snpanel_input` in the base chain and made disable a no-op.
        let out = render(&ruleset("1\tallow\t203.0.113.4\t\ttcp\n"));
        let delete = out
            .find("delete table inet snpanel")
            .expect("must delete the old table");
        let create = out
            .rfind("table inet snpanel {\n")
            .expect("must then create it");
        assert!(delete < create, "the delete has to come first");
        // And the empty declaration before it, so the delete cannot fail on a
        // box that has never loaded the table.
        let declare = out
            .find("table inet snpanel {}")
            .expect("empty declaration");
        assert!(declare < delete);
    }

    #[test]
    fn applying_twice_yields_the_same_ruleset() {
        // Idempotence is the property the delete buys. Rendering is pure, so
        // this checks the text; the container test checks the kernel.
        let rs = ruleset("1\tallow\t203.0.113.4\t\ttcp\n");
        assert_eq!(render(&rs), render(&rs));
        assert_eq!(
            render(&rs).matches("jump snpanel_input").count(),
            1,
            "exactly one jump, however many times this is applied"
        );
    }

    #[test]
    fn renders_a_loadable_looking_ruleset() {
        let out = render(&ruleset("1\tallow\t203.0.113.4\t\ttcp\n"));
        assert!(out.contains("table inet snpanel {"));
        assert!(out.contains("chain snpanel_input {"));
        assert!(out.contains("203.0.113.4"));
        // Braces must balance or nft rejects the whole file.
        assert_eq!(out.matches('{').count(), out.matches('}').count());
    }

    #[test]
    fn allowed_traffic_returns_rather_than_accepts() {
        // C38: fail2ban must still see the packet.
        let out = render(&ruleset("1\tallow\t203.0.113.4\t\ttcp\n"));
        assert!(out.contains("ip saddr @allow4 return"));
        // `policy accept` on the base chain is required and separate (C39):
        // SNPanel must not flip the machine's default policy. What must not
        // appear is a *rule* that accepts, because that short-circuits every
        // other input rule on the box, fail2ban included.
        let accepting_rules: Vec<&str> = out
            .lines()
            .map(str::trim)
            .filter(|l| l.contains("accept") && !l.starts_with("type filter hook"))
            .collect();
        assert!(
            accepting_rules.is_empty(),
            "no rule may accept; found {accepting_rules:?}"
        );
    }

    #[test]
    fn disabling_removes_the_hook_and_keeps_the_chain() {
        // C39: not a policy flip.
        let mut rs = ruleset("1\tallow\t203.0.113.4\t\ttcp\n");
        rs.state = FirewallState::Disabled;
        let out = render(&rs);
        assert!(out.contains("chain snpanel_input"), "the chain stays");
        assert!(!out.contains("hook input"), "but nothing jumps to it");
        assert!(!out.contains("policy drop"), "the policy is never flipped");
        // And with no base chain there must be no terminal drop either.
        assert!(!out.lines().any(|l| l.trim() == "drop"));
    }

    #[test]
    fn enabled_ends_in_a_drop() {
        let out = render(&ruleset(""));
        assert!(out.contains("hook input"));
        assert!(out.lines().any(|l| l.trim() == "drop"));
    }

    #[test]
    fn invalid_conntrack_state_is_dropped() {
        // Present in the bash, missing from the plan's sketch.
        let out = render(&ruleset(""));
        assert!(out.contains("ct state invalid drop"));
    }

    #[test]
    fn icmp_is_returned_so_ipv6_keeps_working() {
        let out = render(&ruleset(""));
        assert!(out.contains("ip protocol icmp return"));
        assert!(
            out.contains("meta l4proto ipv6-icmp return"),
            "dropping ICMPv6 kills neighbour discovery and with it all of IPv6"
        );
    }

    #[test]
    fn port_scoped_denies_do_not_widen_into_whole_host_denies() {
        // The failure this guards against: rendering "deny 10.0.0.0/8 port 22"
        // as a whole-host deny would cut off far more than the rule asks.
        let out = render(&ruleset("1\tdeny\t10.0.0.0/8\t22\ttcp\n"));
        assert!(
            out.contains("10.0.0.0/8 . 22"),
            "must land in the denyp4 set"
        );
        let deny4_block = out
            .split("set deny4 {")
            .nth(1)
            .and_then(|s| s.split('}').next())
            .unwrap_or("");
        assert!(
            !deny4_block.contains("10.0.0.0/8"),
            "and must NOT also land in the whole-host deny set"
        );
    }

    #[test]
    fn ordering_matches_the_iptables_chain() {
        let out = render(&ruleset(
            "1\tallow\t203.0.113.4\t\ttcp\n2\tdeny\t198.51.100.0/24\t\ttcp\n",
        ));
        let pos = |needle: &str| {
            out.find(needle)
                .unwrap_or_else(|| panic!("missing {needle}"))
        };
        // lo, then conntrack, then allow, then deny, then icmp, then ports, then drop.
        assert!(pos("iif lo return") < pos("ct state established"));
        assert!(pos("ct state established") < pos("@allow4"));
        assert!(pos("@allow4") < pos("@deny4"));
        assert!(pos("@deny4") < pos("@block4"));
        assert!(pos("@block4") < pos("ip protocol icmp"));
        assert!(pos("ip protocol icmp") < pos("@protected"));
        assert!(pos("@protected") < out.rfind("drop").unwrap());
    }

    #[test]
    fn protected_ports_appear_in_their_set() {
        let out = render(&ruleset(""));
        let block = out
            .split("set protected {")
            .nth(1)
            .unwrap()
            .split('}')
            .next()
            .unwrap();
        for port in ["22", "80", "443", "465", "587", "2222"] {
            assert!(block.contains(port), "port {port} must be protected");
        }
    }

    #[test]
    fn v6_rules_are_rendered_even_on_a_v4_only_host() {
        // The regression this guards: gating v6 on the host having a global
        // address silently drops an existing v6 rule from rules.tsv during
        // migration. `table inet` costs nothing to carry them.
        let rs = ruleset("1\tallow\t203.0.113.4\t\ttcp\n5\tdeny\t2001:db8::/32\t\ttcp\n");
        assert!(rs.ipv6_enabled, "the default must be on");
        let out = render(&rs);
        assert!(out.contains("2001:db8::/32"), "the v6 rule must survive");
        assert!(out.contains("ip6 saddr @deny6 drop"));
        assert!(out.contains("ip saddr @allow4 return"));
    }

    #[test]
    fn v6_can_still_be_switched_off_explicitly() {
        let mut rs = ruleset("1\tallow\t203.0.113.4\t\ttcp\n");
        rs.ipv6_enabled = false;
        let out = render(&rs);
        assert!(!out.contains("ip6 saddr"));
        assert!(!out.contains("set allow6"));
        assert!(out.contains("ip saddr @allow4 return"));
    }

    #[test]
    fn port_only_allow_rules_open_to_the_world() {
        let out = render(&ruleset("1\tallow\t\t8080\ttcp\n2\tallow\t\t5353\tudp\n"));
        let tcp = out
            .split("set open_tcp {")
            .nth(1)
            .unwrap()
            .split('}')
            .next()
            .unwrap();
        let udp = out
            .split("set open_udp {")
            .nth(1)
            .unwrap()
            .split('}')
            .next()
            .unwrap();
        assert!(tcp.contains("8080"));
        assert!(udp.contains("5353"));
        assert!(
            !tcp.contains("5353"),
            "protocols must not bleed into each other"
        );
    }

    #[test]
    fn an_empty_set_renders_without_an_elements_line() {
        // `elements = { }` is a syntax error in nft.
        let out = render(&ruleset(""));
        assert!(!out.contains("elements = {  }"));
        assert!(!out.contains("elements = { }"));
    }

    #[test]
    fn a_large_blocklist_renders() {
        let mut rs = ruleset("");
        rs.blocklist_v4 = (0..2000)
            .map(|i| IpOrCidr::parse(&format!("10.{}.{}.0/24", i / 256, i % 256)).unwrap())
            .collect();
        let out = render(&rs);
        assert!(out.contains("10.0.0.0/24"));
        assert!(out.contains("10.7.207.0/24"));
        assert!(
            out.contains("auto-merge"),
            "adjacent ranges should collapse"
        );
    }

    #[test]
    fn rules_the_parser_rejects_never_reach_the_ruleset() {
        // Defence in depth for the obvious injection attempt: a value that
        // would close the brace and add its own rule cannot survive IpOrCidr.
        assert!(Rule::parse_line("1\tallow\t1.2.3.4 }; drop; #\t\ttcp").is_none());
        let out = render(&ruleset("1\tallow\t1.2.3.4 }; drop; #\t\ttcp\n"));
        assert!(!out.contains("}; drop"));
    }
}
